---
title: "Resultados de la practica U1.3"
output: 
flexdashboard::flex_dashboard:
orientation: columns
vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### COMPORTAMIENTO DE LOS DESEMPEÑOS DURANTE LOS ÚLTIMOS 20 PERIODOS 

```{r}
library(plotly)
serie_0 <- rnorm(15, mean = 3.5)
serie_1 <- rnorm(15, mean = 3.6)
serie_2 <- rnorm(15, mean = 3.7)
t <- c(1:15)

data <- data.frame(t, serie_0, serie_1, serie_2)

p3= plot_ly(data, x = ~t)
p3= p3 %>% add_trace(y = ~serie_0, name = 'serie 0', mode = 'lines')
p3= p3 %>% add_trace(y = ~serie_1, name = 'serie 1', mode = 'lines+markers')
p3= p3 %>% add_trace(y = ~serie_2, name = 'serie 2', mode = 'markers')
p3= p3 %>% layout(title = "Comparacion de resultados ultimos 2 meses",
xaxis = list(title = "periodo"), 
yaxis = list(title="indicadores"))
p3
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, fig.height=4}
library(ggplot2)
library(plotly)
# datos de estudiantes que cursaron Matemáticas Fundamentales
cc=c(20, 10, 20, 20, 20, 20, 20, 20, 20, 30, 20, 20, 20, 10, 30, 20, 20, 30, 20,
30, 30, 20, 10, 30, 20, 20, 30, 30, 10, 20, 10, 20, 20, 20, 10, 20, 10, 20, 
20, 30, 30, 30, 10, 30, 20, 20, 20, 20, 20, 20, 10, 20, 30, 30, 10, 10, 10, 
20, 10, 20, 10, 30, 20, 10, 20, 30, 10, 30, 30, 30, 20, 30, 30, 30, 30, 30, 
30, 20, 10, 30, 10, 20, 20, 10, 20, 20, 20, 20, 10, 20) 
labs=c("Ing. Industrial","Administración ","Contaduría ")

nf=c(4.1, 2.7, 3.1, 3.2, 3.0, 3.2, 2.0, 2.4, 1.6, 3.2, 3.1, 2.6, 2.0, 2.4, 2.8, 
3.3, 4.0, 3.4, 3.0, 3.1, 2.7, 2.7, 3.0, 3.8, 3.2, 2.2, 3.5, 3.5, 3.8, 3.5, 
3.9, 4.2, 4.3, 3.9, 3.2, 3.5, 3.5, 3.7, 4.1, 3.7, 3.5, 3.6, 3.2, 3.1, 3.4, 
3.0, 3.0, 3.0, 2.7, 1.7, 3.6, 2.1, 2.4, 3.0, 3.1, 2.5, 2.5, 3.6, 2.2, 2.4, 
3.1, 3.3, 2.7, 3.7, 3.0, 2.7, 3.0, 3.2, 3.1, 2.4, 3.0, 2.7, 2.5, 3.0, 3.0, 
3.0, 3.2, 3.1, 3.8, 4.1, 3.7, 3.5, 3.0, 3.7, 3.7, 4.1, 3.7, 3.9, 3.7, 2.0)

op=c(3, 4, 4, 3, 4, 4, 5, 5, 4, 5, 4, 3, 4, 5, 5, 4, 3, 3, 2, 3, 3, 3, 4, 5, 5,
3, 2, 5, 4, 3, 4, 4, 4, 4, 5, 5, 5, 3, 5, 4, 3, 4, 4, 4, 5, 5, 4, 3, 5, 4,
4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 5, 3, 4, 4, 4, 4, 4, 2, 3, 5, 4, 3, 5, 4, 4, 
4, 4, 5, 5, 5, 4, 4, 4, 5, 1, 4, 5, 3, 5, 4)


t3=table(cc,op)
rownames(t3)=c("Ing. Industrial","Administración ","Contaduría ")
colnames(t3)=c("Muy Regular","Regular","Bien","Muy bien","Excelente")
barplot(t3, main="Percepción del resultado obtenido por carrera",
xlab="Carrera",
ylab="Percepcion", col=c("orange","green","blue"))


```

### RENDIMIENTO MATEMÁTICAS FUNDAMENTALES

```{r, fig.height=4}
# Diagrama de puntos
ed=round(rnorm(90,18,1),1) # se genera la variable numérica  edad

plot(ed,nf, 
main="Edad vs Nota final ", 
ylim = c(0,5), 
xlab = "Edad", 
ylab = "Nota final",
col="dodgerblue3",pch=19)
grid()
```